#index:
#    path: /
#    controller: App\Controller\DefaultController::index

add_evenement:
  path: /evenement/add
  methods: [GET]
  controller: App\Controller\EvenementController::addEvenement

show_evenement:
  path: /evenement
  methods: [GET]
  controller: App\Controller\EvenementController::index

add_liste:
  path: /listmusique
  methods: [GET]
  controller: App\Controller\ListMusiqueController::index

show_ListMusique:
  path: /listmusique/{id}
  methods: [GET]
  controller: App\Controller\ListMusiqueController::showListMusique

login:
  path: /login/root
  methods: [GET]
  controller: App\Controller\LoginController::login

logout:
  path: /logout/root
  methods: [GET]
  controller: App\Controller\LoginController::logout
