#index:
#    path: /
#    controller: App\Controller\DefaultController::index

add_evenement:
  path: /evenement/add
  methods: [GET]
  controller: App\Controller\EvenementController::addEvenement

show_evenement:
  path: /evenement
  methods: [GET]
  controller: App\Controller\EvenementController::index
