#index:
#    path: /
#    controller: App\Controller\DefaultController::index

add_evenement:
  path: /evenement/add
  controller: App\Controller\EvenementController::addEvenement

show_evenement:
  path: /
  methods: [GET]
  controller: App\Controller\EvenementController::index

remove_evenement:
  path: /evenement/delete/{id}
  controller: App\Controller\EvenementController::deleteEvenement

add_liste:
  path: /listmusique
  methods: [GET]
  controller: App\Controller\ListMusiqueController::index

show_ListMusique:
  path: /listmusique/{id}
  controller: App\Controller\ListMusiqueController::showListMusique

login:
  path: /login/root
  controller: App\Controller\LoginController::login

logout:
  path: /logout/root
  methods: [GET]
  controller: App\Controller\LoginController::logout

add_musique:
  path: /musique/add
  methods: [GET]
  controller: App\Controller\MusiqueController::addMusique

show_musique:
  path: /musique
  controller: App\Controller\MusiqueController::showMusique

ask_password:
  path: /askpassword/{id}
  controller: App\Controller\EvenementController::askPassword

add_Appartient:
  path: /addAppartient/{id}
  controller: App\Controller\AppartientController:addAppartient
